name: 编译X-wrt

on:
  schedule:
    - cron: 0 4 * * 6
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "Dont care, and don't touch it!"
        required: true
        default: 'false'

env:
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 安装必要软件包
      run: |
         sudo apt-get update
         sudo apt update
         sudo apt upgrade -y
         sudo apt update
         sudo apt install build-essential ecj fastjar file flex g++ gcc-multilib g++-multilib gawk gettext git git-core java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev swig python3 python3-dev python3-distutils python3-pyelftools subversion unzip wget zlib1g-dev rsync qemu-utils zip -y
         sudo apt-get update
         sudo apt-get install -y libfuse-dev neofetch 7zip
         sudo apt update
         sudo apt full-upgrade -y
         sudo neofetch
         sleep 10

    - name: 下载（拉取）源码
      working-directory: /workdir
      run: |
        df -hT $PWD 
        git clone https://github.com/x-wrt/x-wrt.git openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        git fetch origin
        git fetch origin --tags
        git checkout -f $(git describe --tags $(git rev-list --tags --max-count=1))
        
    - name: 下载（拉取）插件
      run: |
         cd openwrt/package/
         git clone https://github.com/garypang13/luci-theme-edge.git
         git clone https://github.com/jerrykuku/luci-theme-argon.git
         git clone https://github.com/jerrykuku/luci-app-argon-config.git
         git clone https://github.com/sirpdboy/luci-theme-opentopd.git
         git clone https://github.com/derisamedia/luci-theme-alpha.git
         git clone https://github.com/derisamedia/luci-app-alpha-config.git
         git clone https://github.com/f8q8/luci-app-filetransfer.git
         git clone https://github.com/kongfl888/luci-app-timedreboot.git
         git clone https://github.com/sirpdboy/luci-app-netdata.git
         git clone https://github.com/zzsj0928/luci-app-pushbot.git
         git clone https://github.com/animegasan/luci-app-wolplus.git
         git clone https://github.com/sirpdboy/luci-app-eqosplus.git
    
    - name: 下载横幅（banner）
      run: |
          cd openwrt/package/base-files/files/etc/
          sudo rm -rf banner
          ls
          wget https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/x-wrt-banner.txt -O banner

#    - name: 加载自定义 Feed源和更新Feed-01
#      run: |
#         cd openwrt
#         sed -i 's/192.168.15.1/192.168.5.1/g' package/base-files/files/bin/config_generate
#         sed -i '1i src-git kenzo https://github.com/kenzok8/openwrt-packages' feeds.conf.default
#         sed -i '2i src-git small https://github.com/kenzok8/small' feeds.conf.default
#         ./scripts/feeds update -a && sudo rm -rf feeds/luci/applications/luci-app-mosdns && sudo rm -rf feeds/kenzo/luci-app-smartdns && sudo rm -rf feeds/luci/applications/luci-app-smartdns
#         sudo rm -rf feeds/packages/net/{alist,adguardhome,mosdns,xray*,v2ray*,v2ray*,sing*,smartdns}
#         sudo rm -rf feeds/packages/utils/v2dat
#         sudo rm -rf feeds/packages/lang/golang
#         git clone https://github.com/kenzok8/golang feeds/packages/lang/golang
#         git clone https://github.com/pymumu/openwrt-smartdns feeds/packages/net/smartdns
#         git clone https://github.com/pymumu/luci-app-smartdns feeds/luci/applications/luci-app-smartdns

    - name: 更新Feed
      run: |
        cd openwrt
        sed -i 's/192.168.15.1/192.168.5.1/g' package/base-files/files/bin/config_generate
        ./scripts/feeds update -a
    
    - name: 安装Feed
      run: |
         cd openwrt
         ./scripts/feeds install -a
         df -hT $PWD

    - name: 下载配置（.Config）
      run: |
         cd openwrt
         wget https://raw.githubusercontent.com/QC3284/openwrt-actions-config/main/x-wrt-action-005.config -O .config
         echo "下载完成"

    - name: 下载包（dl库）
      run: |
         sudo neofetch
         cd openwrt
         make download -j8
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件（make）
      run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
         make -j$(nproc)  || make -j4 V=s || make -j4 V=99
         echo "status=success" >> $GITHUB_STATE
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
         echo 压缩bin目录......
         7zz a -mx9 bin.zip bin
         echo 压缩dl目录......
         7zz a -mx9 dl.zip dl
         echo 完成

    - name: 移动dl.zip，bin.zip
      run: |
         mv openwrt/dl.zip openwrt/bin/targets/ramips/mt7621/
         mv openwrt/bin.zip openwrt/bin/targets/ramips/mt7621/
    
    - name:  检查空间使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传 bin 目录
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: 整理文件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件目录
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: 将固件上传到 cowtransfer
      id: cowtransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)" 
        echo "url=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT

    - name: 将固件上传到 WeTransfer
      id: wetransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "usrl=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT

    - name: 生成发布标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "自动编译" >> release.txt
        echo "注意！本固件只适合型号为Xiaomi cr660x的路由器" >> release.txt
        echo "使用源码：" >> release.txt
        echo "[x-wrt](https://github.com/x-wrt/x-wrt)" >> release.txt
        echo "使用最新标签" >> release.txt
        echo "默认账号/密码：" >> release.txt
        echo "admin/admin" >> release.txt
        echo "SSH默认账号/密码：" >> release.txt
        echo "root/admin" >> release.txt
        echo "注意！！！需要进入界面-系统-管理权页面-开启SSH登录" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件以发布
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
     
    - name: 删除工作流运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: 删除旧版本
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
